src/AB/BlogBundle/Entity/Blog.php
<?php

namespace AB\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Blog
 *
 * @ORM\Table(name="blog")
 * @ORM\Entity(repositoryClass="AB\BlogBundle\Repository\BlogRepository")
   @ORM\HasLifecycleCallbacks()
 */
class Blog
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
   * @ORM\OneToOne(targetEntity="AB\BlogBundle\Entity\Image", cascade={"persist"})
   */
  private $image;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255)
     */
    private $author='Arken';

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="images", type="string", length=255, nullable=true)
     */
    private $images;
    
    /**
    * @var \DateTime
    * @ORM\Column(name="updated_at", type="datetime", nullable=true)
    */
    private $updatedat;
    
    /**
     * @var string
     *
     * @ORM\Column(name="categorie", type="string", length=255)
     */
    private $categorie;
    
     /**
     * @var int
   * @ORM\Column(name="nb_vues", type="integer")
   */
    private $nbvues = 0;
    
    /**
     * Get nbvues
     *
     * @return int
     */
    public function getNbvues()
    {
        return $this->nbvues;
    }
    
    /**
     * Set nbvues
     *
     * @param int $nbvues
     *
     * @return Blog
     */
    public function setNbvues()
    {
        $this->nbvues=$nbvues;
        return $this;
    }
    
    
    
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Blog
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedat;
    }
    
    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Blog
     */
    public function setUpdatedAt($updatedat)
    {
        $this->updatedat = $updatedat;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Blog
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set author
     *
     * @param string $author
     *
     * @return Blog
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return Blog
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set images
     *
     * @param string $images
     *
     * @return Blog
     */
    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Get images
     *
     * @return string
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Set categorie
     *
     * @param string $categorie
     *
     * @return Blog
     */
    public function setCategorie($categorie)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return string
     */
    public function getCategorie()
    {
        return $this->categorie;
    }
    public function __construct()
  {
    // Par défaut, la date de l'article est la date d'aujourd'hui
    $this->date = new \Datetime();
  }
  /**
   * @ORM\Column(name="published", type="boolean")
   */
  private $published = true;

    /**
     * Set published
     *
     * @param boolean $published
     *
     * @return Blog
     */
    public function setPublished($published)
    {
        $this->published = $published;

        return $this;
    }

    /**
     * Get published
     *
     * @return boolean
     */
    public function getPublished()
    {
        return $this->published;
    }
    
    /**
    * @ORM\PreUpdate
    */
    public function updateDate()
  {
    $this->setUpdatedAt(new \Datetime());
  }
    
    public function increaseVues()
    {
    $this->nbvues++;
  }
  public function setImage(Image $image = null)
  {
    $this->image = $image;
  }

  public function getImage()
  {
    return $this->image;
  }

}

src/AB/BlogBundle/Entity/Image.php
<?php

namespace AB\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="AB\BlogBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;

    private $tempFilename;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
    
    private $file;
  
  public function getFile()
  {
    return $this->file;
  }

  public function setFile(UploadedFile $file)
  {
    $this->file = $file;

    // On vérifie si on avait déjà un fichier pour cette entité
    if (null !== $this->url) {
      // On sauvegarde l'extension du fichier pour le supprimer plus tard
      $this->tempFilename = $this->url;

      // On réinitialise les valeurs des attributs url et alt
      $this->url = null;
      $this->alt = null;
    }
  }
  
  /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file) {
      return;
    }

    // Le nom du fichier est son id.sonextension
    $this->url = $this->id.'.'.$this->file->guessExtension();

    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
    $this->alt = $this->file->getClientOriginalName();
  }
  
  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file) {
      return;
    }

    // Si on avait un ancien fichier, on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }
  // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->file->move(
      $this->getUploadRootDir(), // Le répertoire de destination
      $this->url   // Le nom du fichier à créer, ici « id.extension »
    );
  }
  
   /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }
  
  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
    return 'uploads/img';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }
}

src/AB/BlogBundle/Form/BlogType.php
<?php
    
    namespace AB\BlogBundle\Form;
    
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
    use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
    use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
    use Symfony\Component\Form\Extension\Core\Type\SubmitType;
    use Symfony\Component\Form\Extension\Core\Type\TextareaType;
    use Symfony\Component\Form\Extension\Core\Type\TextType;
    use Symfony\Component\Form\Extension\Core\Type\CollectionType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolver;
    
    class BlogType extends AbstractType
    {
        /**
            * @param FormBuilderInterface $builder
            * @param array $options
        */
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
            ->add('date',     DateTimeType::class)
            ->add('title',     TextType::class)
            ->add('author',    TextType::class)
            ->add('categorie', ChoiceType::class, array(
            'choices'  => array(
            'En surface' => 'Surface',
            'Souterrains' => 'Souterrain',
            'Catacombes Paris' => 'Catacombes',
            'Se lancer' => 'Se lancer')))
            ->add('content',   TextareaType::class)
            ->add('published', CheckboxType::class, array('required' => false))
            ->add('image',     ImageType::class)
            /*->add('images', CollectionType::class, array(
            'entry_type'   => ImageType::class,
            'allow_add'    => true,
            'allow_delete' => true
            ))*/
            ->add('Sauvegarder',      SubmitType::class)
            ;
        }
        
        /**
            * @param OptionsResolver $resolver
        */
        public function configureOptions(OptionsResolver $resolver)
        {
            $resolver->setDefaults(array(
            'data_class' => 'AB\BlogBundle\Entity\Blog'
            ));
        }
    }

src/AB/BlogBundle/Controller/BlogController.php
<?php

namespace AB\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use AB\BlogBundle\Form\ContactType;
use AB\BlogBundle\Entity\Contact;

class BlogController extends Controller
{
    public function indexAction(Request $request)
    {
         if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
         $admin=true;
         }
         else
         {
          $admin=false;    
             }
        $tag = $request->query->get('tag');
        $listArticles = $this->getDoctrine()
      ->getManager()
      ->getRepository('ABBlogBundle:Blog')
      ->findBy(
                array('published' => 1), // Critere
                array('date' => 'desc'),        // Tri
                1,                              // Limite
                0                               // Offset
                )
    ;
        $url = $this->get('router')->generate('ab_blog_home');
        return $this->render('ABBlogBundle:Blog:index.html.twig',array(
      'listArticle' => $listArticles,'titre'=>'Derniers Articles :','admin' => $admin
    ));
    }
    public function viewAction($id)
  {
      if($id===0){
        return $this->redirectToRoute('ab_blog_home');
        }
        else{
    $em = $this->getDoctrine()->getManager();

    // Pour récupérer un seul article, on utilise la méthode find($id)
    $article = $em->getRepository('ABBlogBundle:Blog')->find($id);
    $article->increaseVues();
    $em->persist($article);
    $em->flush();
    // $article est donc une instance de A\PlatformBundle\Entity\Blog
    // ou null si l'id $id n'existe pas, d'où ce if :
    if (null === $article) {
      throw new NotFoundHttpException("L'article d'id ".$id." n'existe pas.");
    }
    //$article->getImage()->setUrl('/'.$article->getImage()->getUploadDir().'/'.$article->getImage()->getUrl());//remplace l'url de l'image par l'addresse relative au navigateur
    return $this->render('ABBlogBundle:Blog:view.html.twig', array(
      'article'           => $article
    ));
        }
  }

    public function recentAction()
  {
    // On récupère les données issues de la bdd
    $listArticles = $this->getDoctrine()
      ->getManager()
      ->getRepository('ABBlogBundle:Blog')
      ->findBy(
                array('published' => 1), // Critere
                array('date' => 'desc'),        // Tri
                5,                              // Limite
                0                               // Offset
                )
    ;

    return $this->render('ABBlogBundle:Blog:menu.html.twig', array(
      'listArticle' => $listArticles,'titre'=>'Derniers Articles :'
    ));
  }
  
  public function populaireAction()
  {
    // On récupère les données issues de la bdd
    $listArticles = $this->getDoctrine()
      ->getManager()
      ->getRepository('ABBlogBundle:Blog')
      ->findBy(
                array('published' => 1), // Critere
                array('nbvues' => 'desc'),        // Tri
                5,                              // Limite
                0                               // Offset
                )
    ;

    return $this->render('ABBlogBundle:Blog:menu.html.twig', array(
      // Tout l'intérêt est ici : le contrôleur passe
      // les variables nécessaires au template !
      'listArticle' => $listArticles,'titre'=>'Articles populaires :'
    ));
  }
  
   public function categorieAction($categorie)
  {
    $checkCate = array('Surface','Souterrain','Catacombes','Se lancer');
    if(!in_array($categorie, $checkCate))
    {
        return $this->redirectToRoute('ab_blog_home');
    }
    else
    {
       // On récupère les données issues de la bdd
    $listArticles = $this->getDoctrine()
      ->getManager()
      ->getRepository('ABBlogBundle:Blog')
      ->findBy(
                array('published' => 1,'categorie'=> $categorie), // Critere
                array('date' => 'desc'),        // Tri
                50,                              // Limite
                0                               // Offset
                )
    ;
    //$article->getImage()->setUrl('/'.$article->getImage()->getUploadDir().'/'.$article->getImage()->getUrl());//remplace l'url de l'image par l'addresse relative au navigateur
    return $this->render('ABBlogBundle:Blog:categorie.html.twig', array(
      'listArticle' => $listArticles,'categorie' => $categorie,
    ));
    }
  }
  
  public function aboutAction(Request $request)
  {
    return $this->render('ABBlogBundle:Blog:about.html.twig');
  }
  
  public function contactAction(Request $request)
  {
  
                //On crée un objet Contact
                $contact= new Contact();
                //On crée le Formulaire
                $form = $this->createForm(ContactType::class, $contact);                
                // Si la requête est en POST
                if ($request->isMethod('POST')) {
                    // On fait le lien Requête <-> Formulaire
                    // À partir de maintenant, la variable $contact contient les valeurs entrées dans le formulaire par le visiteur
                    $form->handleRequest($request);
                    if ($form->isValid()) {
                        $contact->setMessage(nl2br($contact->getMessage()));
                        //$blog->getImage()->upload();
                        // On enregistre notre objet $blog dans la base de données, par exemple
                        $em = $this->getDoctrine()->getManager();
                        $em->persist($contact);
                        $em->flush();
                        
                        $request->getSession()->getFlashBag()->add('contact', 'Votre message a bien été envoyé. Nous y répondrons dans les plus brefs délais.');
                        return $this->redirectToRoute('ab_blog_contact');
                    }
                }
                //Sinon on affiche le formulaire
                return $this->render('ABBlogBundle:Blog:contact.html.twig',array(
                'form'=>$form->createView(),
                ));
  }
}

src/AB/BlogBundle/Resources/views/Blog/about.html.twig
{% extends "ABBlogBundle::layout.html.twig" %}

{% block title %} {{parent()}} A propos{% endblock %}
{% block header %}
    {{ parent() }}
    <style type="text/css">
    </style>
{% endblock %}

{% block content %}
{{parent()}}
<div class="col-md-7">
    <h1 class="page-header">A propos</h1>
    <p class="description">
    <h3>Qui suis-je ?</h3>
    Moi c'est Arken, j'ai 20 ans, je suis étudiant en informatique.<br/>
    Depuis quelques années je me suis interessé à ce qu'on appelle l'Urbex, que cela soit les infrastructures urbaines, les bâtiments en construction, les manoirs abandonnés, les anciennes installations millitaires,
    les anciennes mines/carrières et j'en passe... A travers ce blog j'essaie de partager mes explorations et aventures avec vous.
    <h3> A propos de l'Urbex </h3>
    Je vous déconseille de reproduire les différentes explorations que je publie, certains lieux sont dangereux (sol instable par exemple) d'autres sont des propriétés privées.<br/>
    La plupart des lieux visités le sont illégalement et il m'est arrivé de me faire ramener à la sortie plus ou moins gentillement par des gardiens.<br/>
    Si vous souhaitez tout de même "vous lancer" dans l'Urbex je vous donne tous mes conseils dans la catégorie Vous Lancer.
    Vous ne trouverez <b>aucune</b> adresse permettant de localiser un lieu sur mon blog, afin de les préserver d'éventuelles dégradations/pillages. <br/>
    En revanche il est possible (en cherchant bien) de trouver quelques indices, ou en utilisant un cheat code.
    </div>
{% endblock %}
{% block footer%}
{{parent()}}
{% endblock %}

src/AB/BlogBundle/Resources/views/Blog/categorie.html.twig
{% extends "ABBlogBundle::layout.html.twig" %}
{% block title %}{{parent()}} {{ categorie }}{% endblock %}
{% block content %}
{{parent()}}
{% for message in app.session.flashbag.get('notice') %}
        <p class="alert alert-success">{{ message }}</p>
{% endfor %}
<div class="col-md-9 well">
    <div class="page-header">
        <h1>{{categorie}}</h1>
    </div>
        <div class="row">
            {% for article in listArticle %}
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-10">
                            <a  href="{{ path('ab_blog_view', {'id':article.id}) }}">
                            <div class="thumbnail" style="  min-height: 230px;
                                                            background: url(/{{article.image.uploaddir}}/{{article.image.url}});
                                                            background-size: 450px 230px;
                                                            background-repeat: no-repeat;">
                                    <h1 style="font-family: 'Roboto', sans-serif;
                                                font-weight: 1500;
                                                color: white;
                                                text-transform: uppercase;
                                                margin: 0;
                                                position: absolute;
                                                top: 50%;
                                                left: 50%;
                                                font-size: 2.7rem;
                                                transform: translate(-50%, -50%);">{{ article.title }}</h1>
                            </div>
                            </a>
                        </div>  
                        <div class="col-md-1">
                        </div>
                    </div>
                </div>
            {% if loop.index is divisible by(3) %}
        </div>
        <div class="row">
            {% endif %}
            {%else%}
                <h3>Il n'y a pour l'instant aucun article dans cette catégorie. Revenez plus tard !</h3>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}
{% block footer%}
{{parent()}}
{% endblock %}

src/AB/BlogBundle/Resources/views/Blog/contact.html.twig
{% extends "ABBlogBundle::layout.html.twig" %}
{% block head %}
{{parent()}}
<style>
textarea.form-control{
height:280px !important;
}
</style>
{% endblock %}
{% block title %} {{parent()}} Contact{% endblock %}
{% block content %}
{{parent()}}
<div class="col-md-7">
{% for message in app.session.flashbag.get('contact') %}
        <p class="alert alert-success">{{ message }}</p>
{% endfor %}
    <h3 class="page-header">Me Contacter</h3>
    <div class="well">

    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  {{ form_errors(form) }}

  <div class="form-group">
    {{ form_label(form.auteur, "Votre Nom", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    <div class="col-sm-10">
      {{ form_widget(form.auteur, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>
  
  <div class="form-group">
    {{ form_label(form.auteur, "Votre Email", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    <div class="col-sm-10">
      {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>
  
  <div class="form-group">
    {{ form_label(form.auteur, "Votre Message", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    <div class="col-sm-10">
      {{ form_widget(form.message, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>
   <div class="col-sm-2"></div> 
    
  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}

  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
    
    
    
    
    
    </div>
</div>
<div class="col-md-3" style="margin-top:100px;">
<img class="img-responsive" src="{{asset('img/mailbox.jpg')}}" alt="Mailbox"/>
</div>
{% endblock %}
{% block footer%}
{{parent()}}
{% endblock %}

src/AB/BlogBundle/Resources/views/Blog/index.html.twig
{% extends "ABBlogBundle::layout.html.twig" %}

{% block title %} {{parent()}} Accueil{% endblock %}
{% block header %}
    {{ parent() }}
    <style type="text/css">
    </style>
{% endblock %}

{% block content %}
{% if admin==true%}
<a href="{{ path('ab_blog_admin') }}"><h1 class="page-header">Panneau Admin</h1></a><br/>
{% endif %}
{{parent()}}
<div class="col-md-8">
    <h1 class="page-header">Accueil</h1>
    <p class="description">
    Bienvenue sur mon blog, vous y trouverez des articles contant mes explorations.<br/>
    Vous pouvez naviguer entre les différentes catégories en utilisant le menu en haut de la page.<br/>
    Pour toute suggestion / question je vous invite à me l'adresser dans l'onglet Contact du site.<br/>
    Ci-dessous le dernier article publié sur le site : </p>
    
    
    {% for article in listArticle %}
            <div class="page-header">
        <h1>{{article.title}}</h1>
    </div>
    <div>
         <img style="width:100%;max-height:640px;" class="img-responsive" src="{{ asset(article.image.uploadDir ~ '/' ~ article.image.url) }}"  alt="{{article.image.alt}}"/>
    </div>
    <br/>
    <div class="content">
        {{article.content | raw}}
        <div class="row">
        <div class="col-md-9"> 
            </div>
            <div class="col-md-2">
                Publié le {{article.date|date("d:m:Y")}}
            </div>
            <div class="col-md-1">
                Par {{article.author}}
            </div>
            {#<div class="col-md-2">
                {% if article.updatedat!=null %}
                    Modifié le {{article.updatedat|date("d/m/Y")}}
                {% endif %}
            </div>#}
            
        </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}
{% block footer%}
{{parent()}}
{% endblock %}

src/AB/BlogBundle/Resources/views/Blog/layout.html.twig
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Blog - {% endblock %}</title>
  </head>
  <body>

    {% block body %}
    {% endblock %}

  </body>
</html>

src/AB/BlogBundle/Resources/views/Blog/menu.html.twig
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{titre}}</h3>
        </div>
        <div class="panel-body">
            <ul id="menu" class="nav nav-pills nav-stacked">
            {% for article in listArticle %}
                <li><a href="{{ path('ab_blog_view', {'id':article.id}) }}">
                {{ article.title }}
                </a></li>
            {% endfor %}
        </div>
    </div>

src/AB/BlogBundle/Resources/views/Blog/view.html.twig
{% extends "ABBlogBundle::layout.html.twig" %}
{% block title %}{{ article.title}} {% endblock %}
{% block content %}
{{parent()}}

<div class="col-md-9 well">
{% for message in app.session.flashbag.get('notice') %}
        <p class="alert alert-success">{{ message }}</p>
{% endfor %}
    <div class="page-header">
        <h1>{{article.title}}</h1>
    </div>
    <div>
        <img style="width:100%;max-height:640px;" class="img-responsive" src="{{ asset(article.image.uploadDir ~ '/' ~ article.image.url) }}"  alt="{{article.image.alt}}"/>
    </div>
    <br/>
    <div class="content">
        {{article.content | raw }}
        <div class="row">
        <div class="col-md-9 clearfix">
            <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
            <div id="shareBtn" class="fb-share-button">Partager</div>
        </div>
        <div class="col-md-2">
                Publié le {{article.date|date("d/m/Y")}}
        </div>
        <div class="col-md-1">
                Par {{article.author}}
        </div>
            {#<div class="col-md-2">
                {% if article.updatedat!=null %}
                    Modifié le {{article.updatedat|date("d/m/Y")}}
                {% endif %}
            </div>#}
            
        </div>
    </div>
    <div class="row">
    <h4> Les commentaires ont été désactivés jusqu'à nouvel ordre. Pour toute question passez par la page de Contact.</h4>
    </div>
</div>

{% endblock %}
{% block footer%}
{{parent()}}
<script>document.getElementById('shareBtn').onclick = function() {
  FB.ui({
    method: 'share',
    display: 'popup',
    href: '{{ url('ab_blog_view', {'id': article.id})}}',
  }, function(response){});
}
</script>
{% endblock %}